export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";


export const CHECK_ADDRESS_POST_REQUEST = "CHECK_ADDRESS_POST_REQUEST";
export const CHECK_ADDRESS_POST_SUCCESS = "CHECK_ADDRESS_POST_SUCCESS";
export const CHECK_ADDRESS_POST_FAILURE = "CHECK_ADDRESS_POST_FAILURE";

export const DELETE_TOPIC_BY_USER_ID_REQUEST =
  "DELETE_TOPIC_BY_USER_ID_REQUEST";
export const DELETE_TOPIC_BY_USER_ID_SUCCESS =
  "DELETE_TOPIC_BY_USER_ID_SUCCESS";
export const DELETE_TOPIC_BY_USER_ID_FAILURE =
  "DELETE_TOPIC_BY_USER_ID_FAILURE";