//logout and reset the redux store
export const LOGOUT = "LOGOUT";
// register action types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// login request types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// user details request types
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";



export const GENERATE_OTP_BY_EMAIL_REQUEST = "GENERATE_OTP_BY_EMAIL_REQUEST";
export const GENERATE_OTP_BY_EMAIL_SUCCESS = "GENERATE_OTP_BY_EMAIL_SUCCESS";
export const GENERATE_OTP_BY_EMAIL_FAILURE = "GENERATE_OTP_BY_EMAIL_FAILURE";

export const VALIDATE_OTP_BY_EMAIL_REQUEST = "VALIDATE_OTP_BY_EMAIL_REQUEST";
export const VALIDATE_OTP_BY_EMAIL_SUCCESS = "VALIDATE_OTP_BY_EMAIL_SUCCESS";
export const VALIDATE_OTP_BY_EMAIL_FAILURE = "VALIDATE_OTP_BY_EMAIL_FAILURE";